/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;


public class Menu extends javax.swing.JFrame {
Almacen a = new Almacen();
Categoria c= new Categoria();
Empleado e= new Empleado();
Marca m= new Marca();
Producto p= new Producto();
Proveedor pro = new Proveedor();
Venta v = new Venta();
Cliente cli = new Cliente();
    public Menu() {
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        binv = new javax.swing.JMenu();
        bproducto = new javax.swing.JMenu();
        bclientes = new javax.swing.JMenu();
        bpro = new javax.swing.JMenu();
        bempleado = new javax.swing.JMenu();
        bcategoria = new javax.swing.JMenu();
        bmarca = new javax.swing.JMenu();
        bventa = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1176, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        binv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        binv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inventario.png"))); // NOI18N
        binv.setText("Inventario");
        binv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                binvMouseClicked(evt);
            }
        });
        jMenuBar1.add(binv);

        bproducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        bproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        bproducto.setText("Producto");
        bproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bproductoMouseClicked(evt);
            }
        });
        jMenuBar1.add(bproducto);

        bclientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        bclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        bclientes.setText("Clientes");
        bclientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bclientesMouseClicked(evt);
            }
        });
        jMenuBar1.add(bclientes);

        bpro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        bpro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_prov.png"))); // NOI18N
        bpro.setText("Proveedores");
        bpro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bproMouseClicked(evt);
            }
        });
        jMenuBar1.add(bpro);

        bempleado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        bempleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleado.png"))); // NOI18N
        bempleado.setText("Empleados");
        bempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bempleadoMouseClicked(evt);
            }
        });
        jMenuBar1.add(bempleado);

        bcategoria.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        bcategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        bcategoria.setText("Categorias");
        bcategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcategoriaMouseClicked(evt);
            }
        });
        jMenuBar1.add(bcategoria);

        bmarca.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        bmarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/marcas.png"))); // NOI18N
        bmarca.setText("Marcas");
        bmarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmarcaMouseClicked(evt);
            }
        });
        jMenuBar1.add(bmarca);

        bventa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        bventa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas.png"))); // NOI18N
        bventa.setText("Venta");
        bventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bventaMouseClicked(evt);
            }
        });
        jMenuBar1.add(bventa);

        jMenu9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ganancias.png"))); // NOI18N
        jMenu9.setText("Ganancias");
        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void binvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binvMouseClicked
       jDesktopPane1.add(a);
            a.show();
    }//GEN-LAST:event_binvMouseClicked

    private void bproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bproductoMouseClicked

        jDesktopPane1.add(p);
            p.show();
    }//GEN-LAST:event_bproductoMouseClicked

    private void bclientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bclientesMouseClicked
        jDesktopPane1.add(cli);
            cli.show();
    }//GEN-LAST:event_bclientesMouseClicked

    private void bproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bproMouseClicked
       jDesktopPane1.add(pro);
            pro.show();
    }//GEN-LAST:event_bproMouseClicked

    private void bempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bempleadoMouseClicked
      jDesktopPane1.add(e);
            e.show();
    }//GEN-LAST:event_bempleadoMouseClicked

    private void bcategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcategoriaMouseClicked
        jDesktopPane1.add(c);
            c.show();
    }//GEN-LAST:event_bcategoriaMouseClicked

    private void bmarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmarcaMouseClicked
       jDesktopPane1.add(m);
            m.show();
    }//GEN-LAST:event_bmarcaMouseClicked

    private void bventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bventaMouseClicked
        jDesktopPane1.add(v);
            v.show();
    }//GEN-LAST:event_bventaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu bcategoria;
    private javax.swing.JMenu bclientes;
    private javax.swing.JMenu bempleado;
    private javax.swing.JMenu binv;
    private javax.swing.JMenu bmarca;
    private javax.swing.JMenu bpro;
    private javax.swing.JMenu bproducto;
    private javax.swing.JMenu bventa;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
